---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sdqu1oksfu3r/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -r assets $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp scripts.js $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH